2018-02-21T11:29:44.287Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'a1' as the object already exists)
    at /home/hlf/placilo-po-povzetju/angular-app/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-02-21T11:29:44.295Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'a1' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'a1' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/hlf/placilo-po-povzetju/angular-app/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-02-21T13:40:58.316Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '123a' as the object already exists)
    at /home/hlf/placilo-po-povzetju/angular-app/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-02-21T13:40:58.317Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '123a' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '123a' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/hlf/placilo-po-povzetju/angular-app/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
